[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "streamlit>=1.42.1",
    "trafilatura>=2.0.0",
    "xlsxwriter>=3.2.2",
]
